branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode7
cache: 
  - cocoapods
env:
  matrix:
    - TEST_TYPE=ios
    - TEST_TYPE=osx
    - TEST_TYPE=cocoapods
before_install:
- |
  if [ "$TEST_TYPE" = ios ] || [ "$TEST_TYPE" = osx ]; then
    gem install xcpretty -N --no-ri --no-rdoc
  elif [ "$TEST_TYPE" = cocoapods ]; then
    gem install cocoapods --pre --quiet --no-ri --no-rdoc
    pod setup --silent
    pod repo update --silent
  fi
script:
- |
    if [ "$TEST_TYPE" = ios ]; then
      set -o pipefail
      xcodebuild test -project Bolts.xcodeproj -sdk iphonesimulator -scheme Bolts-iOS -configuration Debug -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
    elif [ "$TEST_TYPE" = osx ]; then
      set -o pipefail    
      xcodebuild test -project Bolts.xcodeproj -sdk macosx -scheme Bolts-OSX -configuration Debug GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
    elif [ "$TEST_TYPE" = cocoapods ]; then
      pod lib lint Bolts.podspec
      pod lib lint --use-libraries Bolts.podspec    
    fi
after_success:
- |
    if [ "$TEST_TYPE" = ios ] || [ "$TEST_TYPE" = osx ]; then
      bash <(curl -s https://codecov.io/bash)
    fi
